"""Write the screening record that backs the course's evidence claim.

Outputs:
  * literature/screening_summary.md — sources included by structured screening (grouped by field)
    and the Europe PMC survey counts per field;
  * data/screening_flow.csv — how many records survived each screening stage.

Inputs are the screening outputs of scripts 02-04 and the Crossref verification report of script 01.
"""
import csv, re
from pathlib import Path
root = Path(__file__).resolve().parents[1]
keys = open(root / 'literature/screened_selected_keys.txt').read().split()
rep = {r['key']: r for r in csv.DictReader(open(root / 'literature/verification_report.tsv'), delimiter='\t')}
names = {'molbio': 'Molecular & cell biology', 'biotech': 'Biotechnology & bioprocess', 'pharmacy': 'Pharmacy & pharmacology',
         'microbiology': 'Microbiology & microbiome', 'breeding': 'Plant & animal breeding', 'genetics': 'Genetics',
         'omics': 'Genomics, transcriptomics, proteomics & metabolomics', 'systems': 'Multi-omics & systems biology',
         'screening': 'Functional genomics screens', 'computational': 'Bioinformatics & computational biology',
         'datascience': 'Data science & machine learning', 'medical': 'Medical & clinical sciences',
         'animal': 'Preclinical animal research', 'neuroscience': 'Neuroscience', 'reproducibility': 'Meta-research & reproducibility',
         'reporting': 'Evidence synthesis'}

def esc(s):
    """Plain text for a Markdown table cell: strip any markup and escape the cell separator."""
    return re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', '', s)).replace('|', r'\|').strip()

rows = [rep[k] for k in keys]
assert all(r['theme'] in names for r in rows)

out = ['# Screening record', '',
       'Generated by `scripts/06_screening_tables.py`; do not edit by hand.', '',
       f'## Sources included through structured screening (n = {len(rows)})', '',
       'Citation counts are from Crossref at the time of the search. The full candidate pool',
       '(977 records) is in `screening_pool.csv`; the records passing the scripted title rules are in',
       '`screened_included.csv`.', '',
       '| Field | Title | Year | Key | Cites |', '|---|---|---|---|---|']
for th in names:
    grp = sorted([r for r in rows if r['theme'] == th], key=lambda r: -int(r['cited_by'] or 0))
    for i, r in enumerate(grp):
        out.append(f"| {names[th] if i == 0 else ''} | {esc(r['title'])} | {r['year']} | `{r['key']}` | {r['cited_by']} |")

tot = list(csv.DictReader(open(root / 'data/field_totals.csv')))
yc = list(csv.DictReader(open(root / 'data/field_year_counts.csv')))
out += ['', '## Europe PMC survey results by field', '',
        'Records combining design and field terms in the title, abstract or keywords. Fields overlap.',
        'The fold change compares 2025 with 2005 to reduce small-count instability.', '',
        '| Field | Total | Reviews | % reviews | 2005 | 2025 (fold) |', '|---|---|---|---|---|---|']
for r in sorted(tot, key=lambda r: -int(r['total'])):
    y = {int(x['year']): int(x['hits']) for x in yc if x['field'] == r['field']}
    out.append(f"| {esc(r['field'])} | {int(r['total']):,} | {int(r['reviews']):,} | "
               f"{100 * int(r['reviews']) / int(r['total']):.1f} | {y[2005]:,} | "
               f"{y[2025]:,} ({y[2025] / max(y[2005], 1):.0f}x) |")

core = sum(1 for _ in open(root / 'literature/core_references.tsv')) - 1
flow = [('identified_targeted_title_search', 87892), ('retrieved_top60_per_field', 1080), ('duplicates_removed', 1080 - 977),
        ('screened_scripted_title_rules', 977), ('excluded_scripted', 485), ('assessed_manually', 492),
        ('excluded_manual', 492 - len(rows)), ('included_from_screening', len(rows)),
        ('added_by_curation', core - len(rows)), ('total_sources', core)]
with open(root / 'data/screening_flow.csv', 'w', newline='') as fh:
    w = csv.writer(fh); w.writerow(['stage', 'n']); w.writerows(flow)

out += ['', '## Screening flow', '', '| Stage | n |', '|---|---|'] + \
       [f"| {s.replace('_', ' ')} | {n:,} |" for s, n in flow] + ['']
(root / 'literature/screening_summary.md').write_text('\n'.join(out))
print(dict(flow))
